### ISSUE TITLE
[Webinterface] Prevent the user from accidentally leaving the page during their upload by making them click a popup

### ISSUE THREAD

**Issue by rfornea** [opacity/webinterface#11]
If a user leaves the page while their file is still uploading to the brokers and tangle attachment has not yet begun, their upload will not succeed and they will not get their money back.  

Make it difficult for them to leave the page accidentally during the upload process by having some kind of "Are you sure?" popup.  If they want to abandon their upload and lose their money, they must consciously click "yes" or "ok".

**Comment by CKH4** [comment]
#23 is a decent fix for this. The main problem is determining the difference between programmatic navigation and user initiated ones. In this I only check that the navigation wasn't a PUSH (forward), which could still be triggered if a user manually types in an address.

This could use more work, but due to the complexity between Redux handling the navigation changes, it may require a lot of effort to make a complete solution.
