### ISSUE TITLE
Pasting account handle to login 2x allows login

### ISSUE THREAD

**Issue by funkydrummer** [opacity/webinterface#200]
eg address:
a922ed4bb433d35cb7d530c9badc79cd9851663929df50f4192b1d836314f0b340a8a8caf46dac2fc1ea4d29a271ba5c293a8175804d5c2ae710fd1decd6d926

2x
a922ed4bb433d35cb7d530c9badc79cd9851663929df50f4192b1d836314f0b340a8a8caf46dac2fc1ea4d29a271ba5c293a8175804d5c2ae710fd1decd6d926a922ed4bb433d35cb7d530c9badc79cd9851663929df50f4192b1d836314f0b340a8a8caf46dac2fc1ea4d29a271ba5c293a8175804d5c2ae710fd1decd6d926

**Comment by CKH4** [comment]
This is related to the issue of unpaid accounts being able to log in. The fix for that is the same for this, however, I will add better validation to Opaque so that it's easier to catch errors like this

**Comment by rfornea** [comment]
Since the fix for these two problems is the same, I'm not going to create a separate issue.  I'll just add a comment to this one.  

Neither Fast Nor Far posted this in TG:  
```
Ok, I may have figured out what happened with the previous account that was not working properly. I've paid for it with only 1 gwei so the transaction was very slow (about an hour). at the end was successfully but I think due to this delay the account was labelled as "unpaid". does this make any sense for you ? I mean if you create an account WITHOUT paying for it you can still login (but cannot upload anything).
```
I looked into this to understand what Neither Fast Nor Far was talking about, and if someone signs in with an account they haven't paid for, there is a request to `account-data` and that response should include `paymentStatus: "unpaid"`.  If the payment status is unpaid, we shouldn't take them to the file explorer screen.  Perhaps we should take them back to the invoice screen.  

Here's a hypothetical response when they're trying to sign in with an unpaid account:

```
{"paymentStatus":"unpaid","error":null,"account":{"createdAt":"2019-05-20T18:00:54Z","updatedAt":"2019-05-20T18:00:54Z","expirationDate":"2020-05-20T18:00:54Z","monthsInSubscription":12,"storageLimit":128,"storageUsed":0,"ethAddress":"0x2a29AE739AC6A9Ebf93DB635471f27e09f136796","cost":2}}
```

The request to `metadata/get` will also fail when they haven't paid, because we don't add the metadataKey to badger until they've paid.  

Connor recommends calling `isPaid` before navigating to files screen.
